FROM n8nio/n8n

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_DATABASE=railway
ENV DB_POSTGRESDB_HOST=${{ PGHOST }}
ENV DB_POSTGRESDB_PORT=${{ PGPORT }}
ENV DB_POSTGRESDB_USER=${{ PGUSER }}
ENV DB_POSTGRESDB_PASSWORD=${{ PGPASSWORD }}

ENV N8N_PORT=5678
ENV NODE_ENV=production
ENV WEBHOOK_URL=https://your-railway-app-url
ENV N8N_ENCRYPTION_KEY=your-encryption-key
